# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.station_information import StationInformation  # noqa: F401,E501
from swagger_server import util


class Stations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stations: List[StationInformation]=None):  # noqa: E501
        """Stations - a model defined in Swagger

        :param stations: The stations of this Stations.  # noqa: E501
        :type stations: List[StationInformation]
        """
        self.swagger_types = {
            'stations': List[StationInformation]
        }

        self.attribute_map = {
            'stations': 'stations'
        }
        self._stations = stations

    @classmethod
    def from_dict(cls, dikt) -> 'Stations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stations of this Stations.  # noqa: E501
        :rtype: Stations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stations(self) -> List[StationInformation]:
        """Gets the stations of this Stations.


        :return: The stations of this Stations.
        :rtype: List[StationInformation]
        """
        return self._stations

    @stations.setter
    def stations(self, stations: List[StationInformation]):
        """Sets the stations of this Stations.


        :param stations: The stations of this Stations.
        :type stations: List[StationInformation]
        """

        self._stations = stations
