# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Measure(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hour: str=None, value: str=None):  # noqa: E501
        """Measure - a model defined in Swagger

        :param hour: The hour of this Measure.  # noqa: E501
        :type hour: str
        :param value: The value of this Measure.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'hour': str,
            'value': str
        }

        self.attribute_map = {
            'hour': 'hour',
            'value': 'value'
        }
        self._hour = hour
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Measure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The measure of this Measure.  # noqa: E501
        :rtype: Measure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hour(self) -> str:
        """Gets the hour of this Measure.

        Hour of the data  # noqa: E501

        :return: The hour of this Measure.
        :rtype: str
        """
        return self._hour

    @hour.setter
    def hour(self, hour: str):
        """Sets the hour of this Measure.

        Hour of the data  # noqa: E501

        :param hour: The hour of this Measure.
        :type hour: str
        """

        self._hour = hour

    @property
    def value(self) -> str:
        """Gets the value of this Measure.

        Value of the measure in the hour  # noqa: E501

        :return: The value of this Measure.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Measure.

        Value of the measure in the hour  # noqa: E501

        :param value: The value of this Measure.
        :type value: str
        """

        self._value = value
