# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.measure import Measure  # noqa: F401,E501
from swagger_server import util


class WeatherDayData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, temperatures: List[Measure]=None, humidities: List[Measure]=None):  # noqa: E501
        """WeatherDayData - a model defined in Swagger

        :param _date: The _date of this WeatherDayData.  # noqa: E501
        :type _date: str
        :param temperatures: The temperatures of this WeatherDayData.  # noqa: E501
        :type temperatures: List[Measure]
        :param humidities: The humidities of this WeatherDayData.  # noqa: E501
        :type humidities: List[Measure]
        """
        self.swagger_types = {
            '_date': str,
            'temperatures': List[Measure],
            'humidities': List[Measure]
        }

        self.attribute_map = {
            '_date': 'date',
            'temperatures': 'temperatures',
            'humidities': 'humidities'
        }
        self.__date = _date
        self._temperatures = temperatures
        self._humidities = humidities

    @classmethod
    def from_dict(cls, dikt) -> 'WeatherDayData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The weather_day_data of this WeatherDayData.  # noqa: E501
        :rtype: WeatherDayData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this WeatherDayData.

        Date of related weather data  # noqa: E501

        :return: The _date of this WeatherDayData.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this WeatherDayData.

        Date of related weather data  # noqa: E501

        :param _date: The _date of this WeatherDayData.
        :type _date: str
        """

        self.__date = _date

    @property
    def temperatures(self) -> List[Measure]:
        """Gets the temperatures of this WeatherDayData.


        :return: The temperatures of this WeatherDayData.
        :rtype: List[Measure]
        """
        return self._temperatures

    @temperatures.setter
    def temperatures(self, temperatures: List[Measure]):
        """Sets the temperatures of this WeatherDayData.


        :param temperatures: The temperatures of this WeatherDayData.
        :type temperatures: List[Measure]
        """

        self._temperatures = temperatures

    @property
    def humidities(self) -> List[Measure]:
        """Gets the humidities of this WeatherDayData.


        :return: The humidities of this WeatherDayData.
        :rtype: List[Measure]
        """
        return self._humidities

    @humidities.setter
    def humidities(self, humidities: List[Measure]):
        """Sets the humidities of this WeatherDayData.


        :param humidities: The humidities of this WeatherDayData.
        :type humidities: List[Measure]
        """

        self._humidities = humidities
